---
- name: Include agent
  include: tasks/agent.yml
  when: >
    'agent' in daos_roles

- name: Include server
  include: tasks/server.yml
  when: >
    'server' in daos_roles
    
- name: Include dev
  include: tasks/dev.yml
  when: >
    'dev' in daos_roles

- name: Include debug
  include: tasks/debug.yml
  when: >
    'debug' in daos_roles
